apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aa-1135-dotnet-api-dev
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/intility/aa-1135-dotnet-api:main,
    argocd-image-updater.argoproj.io/update-strategy: digest
    argocd-image-updater.argoproj.io/force-update: "true"
spec:
  project: iuv30012426
  destination:
    namespace: aa1135-dotnet-api-dev
    server: https://kubernetes.default.svc
  # syncPolicy:
  #   automated: {}
  source:
    repoURL: https://github.com/jakoblea2/aa1135-dotnet-api.git
    targetRevision: HEAD
    path: k8s/overlays/development
