apiVersion: apps/v1
kind: Deployment
metadata:
  name: aa-1135-dotnet-api
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: aa-1135-dotnet-api
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
