apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -prod

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: aa-1135-dotnet-api-prod

patches:
  - path: deployment-patch.yaml
  - path: pdb-patch.yaml

configMapGenerator:
  - name: aa-1135-dotnet-api-config
    literals:
      - ASPNETCORE_ENVIRONMENT=Production

# x-release-please-start-version
images:
  - name: aa-1135-dotnet-api
    newName: ghcr.io/intility/aa-1135-dotnet-api
    newTag: 1.0.0
# x-release-please-end
